@startuml
class ClaseDeportiva {
    + Id : int <<get>> <<set>>
    + TipoDeporteId : int <<get>> <<set>>
    + Descripcion : string <<get>> <<set>>
    + FechaHora : DateTime <<get>> <<set>>
    + Lugar : string? <<get>> <<set>>
    + Monitor : string <<get>> <<set>>
    + Nivel : string <<get>> <<set>>
    + PlazasDisponibles : int <<get>> <<set>>
    + PrecioUnitario : decimal <<get>> <<set>>
    + ClaseDeportiva()
    + ClaseDeportiva(descripcion:string, fechaHora:DateTime, lugar:string?, monitor:string, nivel:string, plazasDisponibles:int, precioUnitario:decimal)
    + ClaseDeportiva(descripcion:string, tipoDeporte:TipoDeporte, fechaHora:DateTime, lugar:string?, monitor:string, nivel:string, plazasDisponibles:int, precioUnitario:decimal)
}
ClaseDeportiva o-- "0..* ClasesInscritas" ClaseInscrita
ClaseDeportiva --> "TipoDeporte" TipoDeporte
@enduml