@startuml
class Competicion {
    + Id : int <<get>> <<set>>
    + Lugar : string <<get>> <<set>>
    + Nombre : string <<get>> <<set>>
    + Plazas : int <<get>> <<set>>
    + Precio : float <<get>> <<set>>
}
class "List`1"<T> {
}
Competicion --> "Fecha" DateTime
Competicion --> "TipoDeporte" TipoDeporte
Competicion --> "CompeticionInscripciones<CompeticionInscripcion>" "List`1"
@enduml
