@startuml
class Pista {
    + IdPista : int <<get>> <<set>>
    + NombrePista : string <<get>> <<set>>
    + NPersonas : int <<get>> <<set>>
    + Precio : double <<get>> <<set>>
    + Stock : int <<get>> <<set>>
    + TipoDeporteId : int <<get>> <<set>>
    + Pista()
    + Pista(nombrePista:string, precio:double, nPersonas:int, stock:int)
}
class "IList`1"<T> {
}
Pista o-> "TipoDeporte" TipoDeporte
Pista o-> "PistasReservadas<PistaReservada>" "IList`1"
@enduml
